### ISSUE TITLE
use "chosen" for dropdowns

### ISSUE THREAD

**Issue by tkellen** [bocoup/nest-weekly-review#43]
We just launched this for Admiralty and it is working great!

I'm not sure if this will actually hold up from a performance standpoint given how many of these we'd have on screen, but I suspect it would be a huge help for @mattsurabian, @aprilnicolehart & @JasminRuth if we implemented this.

http://harvesthq.github.io/chosen/

Feel free to assign this to me if you don't have the time/interest in dealing with it.

**Comment by jugglinmike** [comment]
I'm hesitant to use Chosen because it has a hard dependency on jQuery which this application otherwise has no use for. I'd also be concerned about performance--the UI is already quite slow to update for weeks with many developers.

Rather than jumping directly to a specific JavaScript library, I'd like to talk with those folks and learn more about their needs. There may be another approach that fits better in this application.

**Comment by tkellen** [comment]
Closing because I agree!
