### ISSUE TITLE
Employee Over Utilized

### ISSUE THREAD

**Issue by MattSurabian** [bocoup/nest-weekly-review#58]
http://weekly-review.bocoup.com/date/2015-01-18/phase/22/

Can't verify because an employee is over-utilized. Is their anyway to make it easier to see how that over utilization is occurring?

**Comment by MattSurabian** [comment]
Seems in this case it's due to an "other" item on Tim's calendar. I think I can just remove, but yeah might be nice to have some way to reflect these types of conflicts in data other than the generic error message.

**Comment by tkellen** [comment]
This is a bit of a red-herring, that response should never come back so there is no reason to clarify why it is happening.

**Comment by jugglinmike** [comment]
@tkellen I don't understand. Why response should never come back?

**Comment by tkellen** [comment]
The employee over-utilized error @MattSurabian was seeing was a result of incorrectly ordered api calls, not because the employee actually had two conflicting utilizations. As it isn't actually possible to have two conflicting utilizations (on the main calendar, anyway) the only further explanation for this error would be to describe how weekly-review tried to create a utilization before it removed the one it was meant to replace.
