### ISSUE TITLE
Can't Verify Internal Events

### ISSUE THREAD

**Issue by MattSurabian** [bocoup/nest-weekly-review#88]
When trying to verify anyone during Bocoupfest error received is:

```
Error: Cannot verify developer week.
A utilization must be set for every weekday before that week can be verified.
```

![screenshot_2015-03-23_14-22-23](https://cloud.githubusercontent.com/assets/1134260/6787280/1777ce6e-d168-11e4-9df0-88089ade20ab.png)

Test at this URL: http://weekly-review.bocoup.com/date/2015-03-08/phase/26/

**Comment by MattSurabian** [comment]
I suspect this is due to how Internal Events are treated?

**Comment by jugglinmike** [comment]
@MattSurabian I've deployed a fix for this. Would you mind verifying?

By the way: I appreciate you giving me the benefit of the doubt regarding the underlying cause. While I'd love to blame this bug on some complexity in the data model/business logic, the fact that these are internal events is a red herring. The issue was date math, plain and simple. The important detail was that the week in question contained a daylight savings time boundary. This has finally convinced me of the hubris of trying to do it myself, and you'll note that [the fix](https://github.com/bocoup/nest-weekly-review/commit/2b24be03dd6e6b2423e922a1a1b1792bde6cb799) introduces a dependency on [the well-tested Moment.js library](http://momentjs.com/).

**Comment by tkellen** [comment]
This has been resolved.
